HPENetworking/topology

doc/conf.py
test/test_topology_injection.py
test/test_topology_manager.py
test/test_topology_pytest_plugin.py

fix: dev: Fixes to consider new pep8 requirements.

---

lib/topology/platforms/base.py

New default shell API for BaseNode.

new: dev: New API to BaseNode to allow to change the default shell.

---

lib/topology/platforms/shell.py

Some fixes for the new shell API.

fix: dev: Fixing shell command prefixing.

---

lib/topology/platforms/shell.py

Adding documentation for new shell API.

new: doc: Documenting the new shell API.

---

lib/topology/platforms/shell.py

Adding new functionality for shells that also use a username when authenticating.

new: dev: Adding user matching in PExpectShell.

---

doc/user.rst

Some user introduction to the low-level shell API could be useful, this is added here.

new: doc: Adding user documentation for shell API.

---

lib/topology/platforms/base.py
lib/topology/platforms/shell.py

There is unfinished business in this pull request, please take a look into the ``FIXME``.

new: dev: Adding support for low-level shell API logging.

---

lib/topology/platforms/node.py

@carlos-jenkins this went missing when the just merged branch was rebased with master, please review.

fix: dev: Adding missing methods.

---

doc/index.rst
doc/logging.rst
lib/topology/args.py
lib/topology/logging.py
lib/topology/main.py
lib/topology/platforms/node.py
lib/topology/platforms/shell.py
lib/topology/pytest/plugin.py
requirements.dev.txt
test/test_topology_platforms_shell.py

This adds the ``logging`` module to include the functionality of logging for Topology components.
Documentation is still on progress, I'm submitting the request now to make progress on reviewing the code, I'll complete the documentation in the next commits.

Adding logging capabilities

---

lib/topology/platforms/shell.py
test/test_topology_platforms_shell.py

Using ``initial_prompt`` where it should be. This fixes #39 also.

Righting initial_prompt

---

lib/topology/logging.py
lib/topology/pytest/plugin.py
requirements.doc.txt

Fixing API backwards-compatibility issues.

fix: dev: Keeping StepLogger backwards compatible.

---

lib/topology/interact.py
lib/topology/libraries/manager.py
lib/topology/logging.py
lib/topology/manager.py
lib/topology/platforms/node.py
lib/topology/platforms/platform.py
lib/topology/platforms/service.py
lib/topology/platforms/shell.py
lib/topology/platforms/utils.py
lib/topology/pytest/plugin.py

Adding calls for ``super`` in several ``__init__`` methods that were missing it.

fix: dev: Calling super in init.

---

lib/topology/platforms/shell.py

Command to set prompt was sometimes too fast and were sent
before bash turned off echo (stty -echo) resulting in
unwanted information being displayed. This commit makes
sure bash always have time to turn echo off.

fix: dev: Add some sleeps to allow bash to turn echo off

---

lib/topology/platforms/shell.py

Signed-off-by: Matthew Hall <matthew.hall@hpe.com>

Add a dynamic timeout option

---

doc/conf.py
doc/reference.rst
lib/topology/platforms/shell.py
requirements.dev.txt
requirements.doc.txt
test/test_topology_injection.py

Add the ability to customize the terminal regex code for special shells

chg: dev: Customize term codes regex

---

lib/topology/manager.py
lib/topology/platforms/node.py
lib/topology/platforms/shell.py

Signed-off-by: Matthew Hall <matthew.hall@hpe.com>

Add functions for new test specific log

---

lib/topology/manager.py

Signed-off-by: Matthew Hall <matthew.hall@hpe.com>

Make new testlog func private

---

README.rst
lib/topology/__init__.py
lib/topology/platforms/shell.py
lib/topology/pytest/plugin.py
requirements.dev.txt
test/test_topology_pytest_plugin.py

Signed-off-by: Diego Dompe <dompe@hpe.com>

Add support for newer versions of pytest

---

lib/topology/pytest/plugin.py

Allow for unstable backends to try topology build more than once.

new: usr: Add pytest option --topology-build-retries

---

lib/topology/__main__.py

chg: dev: search path for inject attr expanded
