HPENetworking/topology

lib/topology/injection.py, lib/topology/pytest/plugin.py, test/test_topology_injection.py
With this change the attribute injection file can specify relative wildcards and relative paths from the pytest testing directories arguments.
=> chg: dev: Improves file matching for attribute injection using pytest

lib/topology/injection.py, test/test_topology_injection.py
The attribute=value criteria for node matching was too permissive, fixing that. This closes #2.
=> fix: dev: Fixing bad matching for attribute=value criteria.

lib/topology/injection.py
When injection was used against a symbolic link it was not doing any recursion, that's why we need to include this flag in the walk command.
=> fix: dev: Allow walk to iterate through symbolic links

lib/topology/platforms/shell.py, requirements.dev.txt, test/test_topology_platforms_shell.py
So far, Topology shells have only supported one connection per shell.
This adds multiple-connection functionality to the basic shell classes provided.
=> new: dev: Adding support for multiple connections.

lib/topology/platforms/shell.py, test/test_topology_platforms_shell.py
A raise was missing, make it impossible to handle an exception that may be raised in the try block.
=> fix: dev: Adding a missing raise.

lib/topology/platforms/debug.py, lib/topology/platforms/node.py, lib/topology/platforms/service.py
This change is targeted for milestone 1.8
This address #26 
Please merge #25 before this, as it is foundation for this changes.
What was done:
- Split all APIs the BaseNode implements into separated classes.
- Added a new ServicesAPI and a Service entity to manage and register services.
Breaking changes:
It is now mandatory for the Platform Engines nodes to implement a new method:
```python
@abstractmethod
def _get_services_address(self):
"""
Returns the IP or FQDN of the node so users can connect to the
registered services.
.. note::
This method should be implemented by the platform engine base node.
:returns: The IP or FQDM of the node.
:rtype: str
"""
```
For Topology Docker Platform the implementation should be something like:
```python
def _get_services_address(self):
address = …
```
=> new: dev: Services API and APIs refactoring

lib/topology/logging.py
The idea of this is to avoid UnicodeDecodeErrors when a undecodeable
character shows up in the output that is to be kept by the Pexpect
logger by default but to also allow for strict checking if needed.
=> fix: dev: Setting default errors to ignore.

lib/topology/pytest/plugin.py, requirements.dev.txt, test/test_topology_pytest_plugin.py
This makes the ``test_id`` marker with ``pytest > 3.0.0``. It basically uses the same mechanism that the ``record_xml`` fixture (documented [here](http://doc.pytest.org/en/latest/usage.html#record-xml-property)) uses.
I have not found how to make an equivalent test case to the one we used to had, I have added the corresponding ``FIXME`` to the old test case which I have commented out.
This fixes #13.
=> fix: dev: Making test_id marker work with the new Pytest.

lib/topology/logging.py, lib/topology/platforms/shell.py, test/test_topology_platforms_shell.py
This separates the pexpect logfile into two, one for reading and other for sending, allowing for more precise control on what is logged and how it is logged. Is used now to timestamp sent logs, but can be expanded for other purposes in the future.
=> chg: dev: Adding timestamps to logs.

tox.ini
Without -basepython = python3 tox uses de default python of the system; this ensures tox runs with python 3 no matter the system default
=> chg: dev: tox.ini now uses python3 as base

lib/topology/platforms/shell.py
Adding the capability to send control characters to PExpect shells.
Removing fixed dependencies in dev requirements files since we now have daily CI in travis.
This closes #45.
=> Send control

lib/topology/platforms/shell.py
There are still a few edge cases where bash wasn't able to turn off echo before receiving commands, this slight increase in time is to allow bash enough time to always turn echo off as expected.
=> fix: dev: Increased delay_after_echo_off a bit

lib/topology/logging.py, lib/topology/platforms/shell.py
This change adds a new filehandler that doesn't introduce line changes
arbitrarily. Also Add some line changes on known places to keep output
log file readable. With this changes the log file should match
pexpect's command output stream closer.
=> chg: dev: Modify pexpect logger to match underling data stream

lib/topology/platforms/shell.py
The original initial prompt does not match the FORCED_PROMPT, this makes the shell to throw a timeout exception when trying to reconnect to a previously used shell.
=> chg: dev: add FORCED_PROMPT to the initial prompt

.travis.yml, README.rst, lib/topology/platforms/shell.py, requirements.dev.txt, requirements.txt, test/test_topology_platforms_shell.py, tox.ini
This change requires pexpect >= 4.6.
=> fix: usr: Topology shells will now use pexpect poll() to support more than 1024 file descriptors.

lib/topology/manager.py
Currently the bilinks id is the python instance id, this commit set it
to a combination of the port_ids using the same syntax as pyszn
node0:port0 -- node1:port1
=> chg: usr: Set a meaningful identifier for nml bilinks

lib/topology/libraries/utils.py, lib/topology/logging.py, lib/topology/pytest/plugin.py
Starting on pytest 3.9.2 pytest resolves symbolic links:
https://github.com/pytest-dev/pytest/pull/4108/
This causes an uncompatibility with the attribute injection feature
as the paths pytest sees (realpaths) differ from the injected_attr
(abspath) found on the topology_plugin.
I am not sure how this impacts #61 
Also I am concerned, topology currently does not specify a particular pytest version and this only works for pytest > 3.9.2
=> chg: dev: Use realpath for pytest plugin search paths

lib/topology/pytest/plugin.py, requirements.txt
When running topology via the pytest plugin, ignore the same paths
pytest does by using norecursedirs ini option.
Also move topology plugin configuration to sessionstart as logs on
pytest are live only after that point.
Depends on https://github.com/HPENetworking/pyszn/pull/7
=> new: usr: Ignore the same paths pytest ignores

README.rst, lib/topology/__init__.py, lib/topology/pytest/plugin.py, requirements.txt
This new option will allow to pass the path of a directory
where topologies files *.szn will be defined.
=>  Add pytest option --topology-szn-dir

lib/topology/pytest/plugin.py
In latest version of pytest, the 'int' value as type is no longer supported, causing issues when topology is started.
Here is the error observed: 
```
Traceback (most recent call last):
File "/home/dev/ws/topology_vdut/.tox/test/bin/py.test", line 8, in <module>
sys.exit(console_main())
File "/home/dev/ws/topology_vdut/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 197, in console_main
code = main()
File "/home/dev/ws/topology_vdut/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 155, in main
config = _prepareconfig(args, plugins)
File "/home/dev/ws/topology_vdut/.tox/test/lib/python3.8/site-packages/_pytest/config/__init__.py", line 337, in _prepareconfig
config = pluginmanager.hook.pytest_cmdline_parse(
File …
```
=> fix: dev: Move argparse type from 'int' to int

lib/topology/args.py, tox.ini
* Remove distutils references (it was removed on python3.12)
* Add setuptools as dependency on tox environments (see https://github.com/python/cpython/issues/95299)
=> Support python 3.12

lib/topology/manager.py, lib/topology/platforms/debug.py, lib/topology/platforms/platform.py
This additional step allows the user to take decisions before trying to build the topology and figuring out it is not possible too late.
=> Add a step before build to resolve the topology graph

lib/topology/platforms/shell.py
The current regex fails to clear some ANSI escape characters from the
terminal output. This commit adds a more generic pattern to catch these
cases.
Trying to use a docker node running Ubuntu 22.04 it was found that the
get_response command was returning extra characters in the output.
Behavior not found on Ubuntu 20.04.
Example:
When running the command `send_command('which catchsegv', matches=['@~~==::BASH_PROMPT::==~~@'],
newline=True, timeout=None)`, and then  `get_response()`, the output would
be `04l/usr/bin/catchsegv04h`. Notice the extra characters `04l` and `04h`
wrapping the output. These correspond to ANSI escape characters leftovers.
For example, the current pattern would leave in `49h` if `ESC[?1049h` was
received. With the updated pattern the whole escape sequence is …
=> Update regex to parse terminal output

lib/topology/libraries/manager.py, lib/topology/platforms/manager.py, lib/topology/platforms/utils.py, requirements.txt
```sh 
----/lib/python3.12/site-packages/topology/platforms/manager.py:31: UserWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html. The pkg_resources package is slated for removal as early as 2025-11-30. Refrain from using this package or pin to Setuptools<81.
from pkg_resources import iter_entry_points
```
=> Replace pkg_resources with importlib.metadata for entry point handling

lib/topology/__init__.py, lib/topology/pytest/__init__.py, lib/topology/pytest/plugin.py, requirements.txt, test/szn/ring.szn, test/test_topology_id.py, tox.ini
Now when --topology-group-by-topology pytest
option is provided, any tests that share
the same topology string, szn and injected
attributes are run using the same topology
manager instance. This means the topology
is built only once per group of tests
instead of once per test, reducing the
execution time.
In addition, --topology-topologies-file
controls the path to a json file where the
info of each topology group and its
respective tests is written.
=> Add option to group tests by topology

lib/topology/__init__.py, lib/topology/pytest/plugin.py
This allows other hooks and pytest fixtures obtain information about the topology.
=> Save topology manager instance within the pytest plugin

lib/topology/__init__.py, lib/topology/pytest/plugin.py
This causes the pytest topology fixture to run before any test instead of before any module. The change takes care of keeping the same behavior of building the topology once per module when not grouping by topology.
=> Change topology fixture scope from module to function
